---

- name: "Listing packages using package_facts"
  hosts: test
  become: true
  tasks:
    - name: "listing docker package in a instance"
      package_facts:
        manager: auto
        strategy: all
      register: list_pack

    - debug:
        msg: "{{list_pack}}"


    - name: "checking for docker package"
      when: "'docker' in ansible_facts.packages"
      debug:
        msg: "Docker is available in server"

    - name: "Installing docker if not available"
      when: "'docker' not in ansible_facts.packages"
      shell: amazon-linux-extras install docker -y

    - name: "checking for Apache package"
      when: "'httpd' in ansible_facts.packages"
      debug:
        msg: "Apache is available in server"

    - name: "Installing Apache"
      when: "'httpd' not in ansible_facts.packages"
      yum:
        name: httpd
        state: present
